# Generated by Django 3.1 on 2020-08-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowtext',
            name='body',
            field=models.CharField(max_length=100),
        ),
    ]
